module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    testMatch: ['**/*.steps.ts', '**/*.test.ts'],
    setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
    collectCoverageFrom: ['src/**/*.ts', '!src/**/*.d.ts', '!src/index.ts', '!src/app.ts'],
    coverageDirectory: './coverage/',
    collectCoverage: true,
    moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1',
        '^@controllers$': '<rootDir>/src/controllers',
        '^@controllers/(.*)$': '<rootDir>/src/controllers/$1',
        '^@middlewares$': '<rootDir>/src/middlewares',
        '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
        '^@database$': '<rootDir>/src/database',
        '^@database/(.*)$': '<rootDir>/src/database/$1',
        '^@util$': '<rootDir>/src/util',
        '^@util/(.*)$': '<rootDir>/src/util/$1',
        '^@lib$': '<rootDir>/src/lib',
        '^@lib/(.*)$': '<rootDir>/src/lib/$1',
        '^@schemas$': '<rootDir>/src/schemas',
        '^@schemas/(.*)$': '<rootDir>/src/schemas/$1',
        '^@types$': '<rootDir>/src/@types',
        '^@types/(.*)$': '<rootDir>/src/@types/$1',
    },
    testResultsProcessor: 'jest-junit',
    reporters: ['default', ['jest-junit', { outputDirectory: 'test-results', outputName: 'test-report.xml' }]],
    testTimeout: 10000,
    verbose: true,
    clearMocks: true,
    restoreMocks: true,
};
